// frontend/console/src/layout/index.vue
<script lang="ts" setup>
import { ref } from "vue";
import SideBar from "@/layout/SideBar/index.vue";
import HeaderBar from "@/layout/HeaderBar/index.vue";

const collapsed = ref<boolean>(false);
</script>

<template>
  <a-layout style="min-height: 100vh">
    <a-layout-sider v-model:collapsed="collapsed" collapsible>
      <SideBar />
    </a-layout-sider>
    <a-layout>
      <a-layout-header style="background: #fff; padding: 0">
        <HeaderBar />
      </a-layout-header>
      <a-layout-content style="margin: 0 16px">
        <a-breadcrumb style="margin: 16px 0">
          <a-breadcrumb-item>User</a-breadcrumb-item>
          <a-breadcrumb-item>Bill</a-breadcrumb-item>
        </a-breadcrumb>
        <router-view></router-view>
      </a-layout-content>
      <a-layout-footer style="text-align: center">
        Ant Design ©2018 Created by Ant UED
      </a-layout-footer>
    </a-layout>
  </a-layout>
</template>

<style lang="scss" scoped></style>

// frontend/console/src/layout/index.tsx
import React, { useState } from "react";
import { Breadcrumb, Layout } from "antd";
import { Outlet } from "react-router-dom";
import SideMenu from "./SideMenu";

const { Header, Content, Footer, Sider } = Layout;

const AppLayout: React.FC = () => {
    const [collapsed, setCollapsed] = useState(false);

    return (
        <Layout style={{ minHeight: "100vh" }}>
            <Sider collapsible collapsed={collapsed} onCollapse={(value) => setCollapsed(value)}>
                <div
                    style={{
                        lineHeight: "64px",
                        height: "32px",
                        margin: "16px",
                        backgroundColor: "#fff3",
                    }}
                ></div>
                <SideMenu />
            </Sider>
            <Layout>
                <Header style={{ paddingLeft: "16px", background: "#fff" }}>
                    <Breadcrumb style={{ lineHeight: "64px" }}>
                        <Breadcrumb.Item>User</Breadcrumb.Item>
                        <Breadcrumb.Item>Bill</Breadcrumb.Item>
                    </Breadcrumb>
                </Header>
                <Content
                    style={{
                        margin: "16px",
                        minHeight: "calc(100% - 144px)",
                        backgroundColor: "#ccc",
                    }}
                >
                    <Outlet></Outlet>
                </Content>
                <Footer style={{ textAlign: "center", padding: 0, lineHeight: "48px" }}>
                    Ant Design ©{new Date().getFullYear()} Created by Ant UED
                </Footer>
            </Layout>
        </Layout>
    );
};

export default AppLayout;
